name: ember
description: A Flutter plugin designed for flutter flame and bonfire to allow users to create their own levels using tile sheets and sprite sheets.
version: 0.0.1
repository: https://github.com/Knightro63/ember

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  http: ^1.1.0
  vector_math: ^2.1.4
  path: ^1.8.3
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3